Nuevos canales #269
PyBAQ/django-quilla-web pull request #270
Opened 2021-02-19 20:08 UTC by jorueda

# Pull request

Closes #269 

## Observaciones

Se adiciona canales de WhatsApp y Telegram, se adiciona que los enlaces abran en una pestaña nueva.

2021-02-19 20:09 UTC, jorueda commented
Muestra el icono de WhatsApp pero no muestra el icono de Telegram.

2021-02-22 20:47 UTC, Scot3004 commented
Por favor actualiza font awesome a la versión 4.7.0, reemplazando el archivo `assets/css/font-awesome.min.css`

2021-02-22 20:49 UTC, Scot3004 requested changes
Por favor cuando generes una rama trata que sea sobre la ultima versión de master, en este pull request adicionaste contenido de #268, Por otro lado considero que lo del icono de telegram se puede arreglar actualizando font-awesome sugiero la versión 4.7.0 que no tiene un breaking change que implementaron para la versión 5

2021-02-22 23:12 UTC, pyjavo commented
Se esperan estos cambios en #271

2021-02-22 23:12 UTC, closed without merging