Nuevos canales #269
PyBAQ/django-quilla-web pull request #271
Opened 2021-02-22 23:10 UTC by jorueda

# Pull request

Closes #269 

## Observaciones

Se adicionan los nuevos canales de WhatsApp y Telegram. Se corrige enlace de Slack que no estaba funcionando.

2021-02-24 23:29 UTC, Scot3004 commented
Veo que aplicaste el cambio que sugerí, pero no parece haber funcionado :(

2021-03-14 04:49 UTC, jorueda commented
Se actualizan archivos fontawesome version 4.7.0 y queda funcionando el icono de Telegram. Previamente se había actualizado el archivo font-awesome.min.css.

2021-03-15 15:58 UTC, pyjavo requested changes
¡Perfecto! Ya que estamos en esto, ¿qué tal si actualizamos el icono de meetup? @jorueda:

- Borrar la imagen `/img/meetup.png`
- Reemplazar con el icono de meetup de fontawesome https://fontawesome.com/v4.7.0/icon/meetup

2021-03-15 21:05 UTC, jorueda commented
Se adiciona cambio de icono de meetup a fontawesome

2021-03-15 21:08 UTC, Scot3004 commented
Excelente trabajo!

2021-03-15 21:09 UTC, Scot3004 approved these changes

2021-03-15 21:19 UTC, pyjavo approved these changes

2021-03-15 21:20 UTC, merged