Actualizacion fotos colaboradores
PyBAQ/django-quilla-web pull request #273
Opened 2021-03-16 22:51 UTC by jorueda

# Pull request

Closes #272 

## Observaciones

Se actualizan las fotos de los colaboradores en la sección nosotros. Se adiciona nueva sección Colaboradores previos.

2021-03-16 23:26 UTC, Scot3004 commented
Me sorprende tu rapidez de implementación, sin embargo creo que los miembros antiguos quedan mejor en un bloque de texto y solo los nombres, por hacer la mencion, por que asi como lo envias, da la impresión que estan activos

2021-03-17 01:38 UTC, jorueda commented
Se envía Colaboradores previos sólo texto.

2021-03-17 14:24 UTC, Scot3004 approved these changes
Me encanta como quedo 🥇

2021-03-17 15:31 UTC, pyjavo requested changes
¡Se ve super! Sin embargo, por favor revisar:

1. Favor subir una imagen con menos peso. Usando herramientas como https://imagecompressor.com/ se puede reducir el peso en un 35% a una calidad del 85
2. Actualizar esta rama con master. No aparecen los canales de whatsapp, telegram y el nuevo icono de meetup
3. Lo que está rompiendo la traducción en inglés (aparece ahora texto en español)

2021-03-22 22:12 UTC, closed without merging