Pytest selenium setup
PyBAQ/django-quilla-web pull request #295
Opened 2021-06-30 03:15 UTC by Scot3004

# Pull request

Closes #64 

## Observaciones

Ejecución de tests automatizados

2021-07-12 22:05 UTC, pyjavo requested changes
- ¿Qué propósito tiene el archivo de configuración .vscode/settings.json?
- ¿Python Medellín?

2021-07-12 22:05 UTC, pyjavo commented on tests/test_home.py
> +    assert selenium.find_element_by_tag_name('h1').text == "Python Medellin."
No entiendo el propósito del "Python Medellin" en esta prueba

2021-07-12 23:55 UTC, Scot3004 commented
En serio se fue eso :o

2021-08-02 20:51 UTC, pyjavo commented
Quedo pendiente del cambio y de que se actualice esta rama con los cambios mas recientes

2021-08-19 00:06 UTC, Scot3004 commented on tests/test_home.py
> +    assert selenium.find_element_by_tag_name('h1').text == "Python Medellin."
Ni yo :)

2021-08-19 01:15 UTC, pyjavo requested changes
Por fa quita el archivo de configuración de vscode .vscode/settings.json

2021-09-07 19:41 UTC, pyjavo approved these changes

2021-09-07 19:41 UTC, merged