Nuevo post llamado Caminemos Juntos: Primer paso.
PyBAQ/django-quilla-web pull request #300
Opened 2021-07-24 17:51 UTC by andresperezcera

# Pull request
## Observaciones

Añade el post para el blog llamado Caminemos Juntos: Primer paso.

2021-07-28 15:23 UTC, pyjavo requested changes
¡Super @andresperezcera! Me gusta la forma como lo redactaste y que es fácil y ameno de leer. 😄

Sin embargo, tengo unos puntos que considero podrían mejorar tu colaboración:

1. La imagen principal podría bajar de peso. Considero que 700KB es mucho. En https://imagecompressor.com/ le pude bajar el peso a 260KB.
2. Se ven los cambios en el desarrollo del código pero no se ven los outputs de dichos cambios.
3. Para ser un primer paso, incluir PIP me parece complicar un poco el asunto, teniendo en cuenta que es **el 1er paso** (además de que no queda claro que hace la librería instalada por falta de outputs). Si se va a incluir PIP, creo que debería mostrarse como se usa y para qué, de lo contrario
4. Los enlaces a los "docs" no apunta a la documentación oficial de python sino a la página https://www.w3schools.com/. En ese caso, no se debería llamar docs. Por otro lado, creo que dichos enlaces podrían incluirse en el texto de una forma más orgánica. xxx

(xxx) Si el uso de PIP está inspirado en Dive into Python, no queda claro cuál es "el espíritu del libro" . Un posible arreglo sería añadir una breve explicación al respecto. Ej:

- _Esta serie de artículos van un poco en el espíritu del libro Dive Into Python 3, el cual es un libro que se basa en enseñar a través de ejercicios con un alto componente investigativo por parte de los estudiantes..._
- _Esta serie de artículos van un poco en el espíritu autodidacta e investigativo del libro Dive Into Python 3,..._

2021-07-29 04:46 UTC, andresperezcera commented
@pyjavo Intento atacar un poco de los problemas de forma que mencionas:
 
1. Se redujo la imagen.
2. Se agregaron los outputs.
3. Incluyo PIP haciendo la salvedad que es un overkill ahora, un poco a manera de abrebocas de que no todo tiene que programarse desde cero.
4. Trato de vincularlo todo mas organicamente y explicco que se incluye w3schools por su simplicidad.
5. Incluyo mi interpretación de la filosofía/espíritu de "Dive Into Python3".

Algo que no he incluido allí, pero creo que será util mas adelante es que he creado un repositorio con los scripts de este articulo para facil ejecución en [andresperezcera/pybaq_caminemos_juntos](https://github.com/andresperezcera/pybaq_caminemos_juntos). A medida que el grupo de articulos crezca, se podrán nutrir y espero que otros miembros de la comunidad aporten formas mas pythonicas de resolver algunos puntos.

2021-07-29 15:46 UTC, Scot3004 commented
Esta genial 😄

2021-07-31 21:57 UTC, pyjavo approved these changes
¡Perfecto!

Una duda ¿qué hace este archivo `../primer-paso.png:Zone.Identifier`?

2021-08-01 01:50 UTC, andresperezcera commented
> ¡Perfecto!
> 
> Una duda ¿qué hace este archivo `../primer-paso.png:Zone.Identifier`?

Eso es un problema de WSL. porque hice una transferencia de windows a WSL y viceversa. Tengo que eliminarlo desde windows.

https://github.com/microsoft/WSL/issues/4609

2021-08-02 20:44 UTC, pyjavo commented
@andresperezcera vale. La próxima vez te recomiendo trabajar tus PRs en una rama diferente a master, en caso se dañe algo

2021-08-02 20:49 UTC, merged