Boostrap5
PyBAQ/django-quilla-web pull request #314
Opened 2022-03-04 02:11 UTC by Scot3004

# Pull request

Closes #290 

## Observaciones

Work in progress, aca en este PR aparecen algunos de los cambios visuales propuestos en figma, ya pasando el sitio web a boostrap 5 como apunte, el hover de la sección de nosotros no he podido implementarlo, sin embargo, creo que con la solución de poner los iconos abajo puede funcionar el diseño, por otro lado se cambian totalmente las tipografias, esto esta sujeto a discusión, por lo pronto deje las que trae por defecto boostrap 5
La página de contacto aun no ha sido reacondicionada al diseño, dado que estoy a la espera que el señor Jorge concluya la tarea de actualizar font-awesome dado que en el figma hay que agregar nuevos iconos, esto mismo aplica para los blog posts que tambien la idea es adicionarle iconos

2022-03-04 23:22 UTC, Scot3004 commented
El navbar no se está abriendo correctamente en móviles revisar este ejemplo https://getbootstrap.com/docs/5.1/examples/navbar-fixed/

2022-03-05 01:37 UTC, pyjavo commented
Lo convertí a draft hasta que ya esté listo

2022-03-05 21:56 UTC, Scot3004 commented
Listo, ya tiene todo lo que el sitio web tiene al dia de hoy

2022-03-05 22:11 UTC, pyjavo commented
Una pregunta @Scot3004 

¿qué hay de las tipografías?

h1, h2, h3, h4, h5, h6 {
    font-family: "Raleway",sans-serif;
}
body, p, etc..... {
    font-family: "Lato",sans-serif;
}

2022-03-05 22:23 UTC, Scot3004 commented
Tambien habia olvidado las tipografias, Como las repartimos?
Me faltaban los javascript, por eso no funcionaba el toogle, resolviendo

2022-03-05 22:32 UTC, pyjavo commented
Entiendo. Opino que las dejemos como estaban, es decir, Raleway para titulos y Lato para body, p...

2022-03-05 23:09 UTC, pyjavo commented
¿Son ideas mías o las tipografías no coinciden aún?

En la inicial mira como la letra **"a"** tiene una colita al final (así como la **"d"**)para la etiqueta H4 (Comunidad)

<img width="372" alt="inicial" src="https://user-images.githubusercontent.com/3085051/156902650-d9f13835-3252-489f-abc4-70af5603faed.png">

Mientras que en la nueva la misma palabra se ve diferente a pesar de ser Raleway

<img width="383" alt="Captura de Pantalla 2022-03-05 a la(s) 6 05 16 p  m" src="https://user-images.githubusercontent.com/3085051/156902670-32dfa2dd-7ec7-4fc7-bc74-8ba64df974f0.png">

Lo mismo parece suceder con el párrafo

2022-03-05 23:13 UTC, pyjavo commented
Además de los colores que no son completamente negros (asumo que es un WIP).

p viene siendo color: #384452; y el H* no se

2022-03-05 23:19 UTC, Scot3004 commented
Respecto a la tipografia ya verifique y me sale raleway y renderiza correcto
en cuanto a los colores, explicitamente estaba en _base.scss el cual borre sin piedad, consideras mejor ese gris o un negro?, dejarlo negro fue adrede por que es el color que genera mejor contraste, pero podemos poner el color #384452 si consideras que se ve mejor

2022-03-05 23:20 UTC, Scot3004 commented
Y ya que mencionamos ese tema de los colores, de que color crees queda mejor el navbar?

2022-03-05 23:29 UTC, pyjavo commented
Los colores que estaba antes se veían mejores (gris se ve mejor que negro). Mi sugerencia es que revivas el _base.scss porque hay varias cositas desalineadas también (el subtitulo de los blogs por ejemplo)

2022-03-05 23:47 UTC, pyjavo commented
Gracias. Ahora, ¿no te parece extraño eso? A pesar de que "renderiza correcto" no se ven igual las tipografías 🧐

2022-03-06 05:28 UTC, Scot3004 commented
![Screenshot_2022-03-06-00-27-55-374_com.android.chrome.jpg](https://user-images.githubusercontent.com/1175402/156910498-e1ca335e-f767-410a-844f-37fdb4b97946.jpg)
Toca corregir el botón del navbar en móviles

2022-03-08 15:23 UTC, pyjavo requested changes
- Arreglar el menu en móviles
- El problema de la tipografía persiste (Raleway y Lato no se renderizan correctamente)

2022-03-08 15:25 UTC, pyjavo commented
Hice pruebas en una máquina Linux desde un navegador firefox y el problema de la tipografía persiste. Al inspeccionar elementos, noté que en el deploy se usa 'sans serif' en vez de Lato por alguna razón:

## Página actual
![inicial_pybaq-min](https://user-images.githubusercontent.com/3085051/157268924-4e968827-f5dd-49fe-9e4e-67c00b1662ce.jpg)

## Deploy de versión con bootstrap 5
![deploy_pybaq-min](https://user-images.githubusercontent.com/3085051/157268993-0dbc3228-2a0c-46a9-8798-29aa68ef1f36.jpg)

2022-03-11 12:30 UTC, Scot3004 commented
Resuelto el tema de las tipografias en el anterior css se importaban con @import, reemplazado por un llamado explicito al invocar los archivos css
Se cambio el color $blue-light por $blue-medium para generar un mejor contraste, en los titulos pasa de AA a AAA y para el bloque de featured post ya no hay incidentes de accessibilidad según firefox
El botón del navbar (navbar-toggler) ya es visible, los estilos personalizados se cambiaron por variables scss de boostrap5

2022-03-11 16:12 UTC, pyjavo requested changes
Gracias Sergio por los cambios. Ahora solo faltaría el tema de la diagramación y la alineación del footer y la página de contacto. Adjunto imágen de ambos footer como referencia:

<img width="1242" alt="comparación_footers-min" src="https://user-images.githubusercontent.com/3085051/157904246-85ea92a3-ac98-40fd-a017-7f4c7135e5d6.png">


### Consulte a un diseñador de interfaces y esto fue parte de lo que hablamos:

_**Javier**: A mi me parece mejor como se ve el inicial, todo alineado a la izquierda. Pero el porque, no sabría decirle o o no se si esté yo equivocado y no haya problema. ¿Tu qué opinas?_

_**Diseñador**: Concuerdo, es una mala costumbre tratar de centrar todo siempre, la lectura es ideal si es de izquierda a derecha, y en temas creativos... el diseño web se trata mas bien de ocupar de forma inteligente un grid imaginario entoces justificando todo a la izquierda quedan más claros los límites de los párrafos. 
pd: las líneas las dejaría de 1px_

_**Javier:** ¿Entonces lo mismo aplicaria para la página de contacto que tiene el mismo problema?._

_**Diseñador:** Si_

2022-03-11 23:11 UTC, Scot3004 commented
Entonces alinear a la izquierda el footer y el contacto

2022-03-11 23:13 UTC, Scot3004 commented
Entonces la idea es dejar las líneas como estaban?

2022-03-11 23:20 UTC, pyjavo commented
Si. Alinear a la izquierda como estaban.

Además, te sugeriría dejarlo como estaba el resto del diseño, porque si recuerdas lo que hablamos, se debe hacer notar la diferencia entre el título y el cuerpo. (Es decir, respetar la decisión inicial de que los títulos del footer estaban en blanco y el cuerpo del texto en otro color en el párrafo.

(Y respetando también las decisiones que tomaste para cumplir la accesibilidad jeje)

2022-03-14 21:51 UTC, pyjavo approved these changes
Por mi parte lo veo bien 👍

2022-03-14 21:52 UTC, pyjavo commented
¿Tu qué opinas @jorueda ? ¿Alguna sugerencia adicional?

2022-03-15 23:05 UTC, jorueda commented
Sugeriría actualizar el font de la página (quizás en un futuro Pull Request), el font actual la hace ver desactualizada. Vi uno en una página que se llama https://geekflare.com/ pero parece ser propietario.

2022-03-17 04:59 UTC, pyjavo commented
Cross post:
```
scot3004 — 03/14/2022
Pido disculpa por un pr tan grande, pero la tarea lo ameritaba
```

Gracias @Scot3004

2022-03-17 04:59 UTC, merged

2022-04-15 00:48 UTC, pyjavo commented
@Scot3004 Una pregunta
¿qué herramienta usaste para probar la accesibilidad de los elementos del sitio web?

2022-04-15 01:05 UTC, Scot3004 commented
Firefox tiene un visor de accesibilidad, Chrome tambien y la w3c tiene otro

2022-04-15 01:08 UTC, Scot3004 commented
![image](https://user-images.githubusercontent.com/1175402/163501923-6df1bdfa-95fc-4fde-a283-0bb8ae2e5a4e.png)
Asi se puede ver rapidamente en chrome, con inspeccionar elemento